const constants = {
    LOAD_EXERCISES: "LOAD_EXERCISES",

    LOAD_MUSCLE_GROUPS: "LOAD_MUSCLE_GROUPS",

    ADD_SET: "ADD_SET",
    LOAD_SETS: "LOAD_SETS",
    
	ADD_WORKOUT_EXERCISE: "ADD_WORKOUT_EXERCISE",
    LOAD_WORKOUT_EXERCISES_FOR_DATE: "LOAD_WORKOUT_EXERCISES_FOR_DATE",
    LOAD_TODAYS_WORKOUT_EXERCISES: "LOAD_TODAYS_WORKOUT_EXERCISES"

};

export default constants